### ISSUE TITLE
Wrong Host header send

### ISSUE THREAD

**Issue by atinux** [electerious/ackee-tracker#10]
Hi there 👋

Great work on ackee, I started to use it for NuxtJS examples.

We encountered one issue today on our first example: https://xr8nr.sse.codesandbox.io

We have a CORS error, and it seems that no HOST is sent:
![Screenshot 2020-03-24 at 17 56 42](https://user-images.githubusercontent.com/904724/77454553-f81a1f80-6df8-11ea-9da0-ef6a6f9180c8.png)

When we setup the `ACKEE_ALLOW_ORIGIN` to `"https://xr8nr.sse.codesandbox.io"` on our Heroku (https://nuxt-ackee.herokuapp.com), we had a CORS error, so we set it to `*`.

When looking at the request headers on Chrome, we have the wrong `host` header:
![Screenshot 2020-03-24 at 17 41 37](https://user-images.githubusercontent.com/904724/77453836-103d6f00-6df8-11ea-863f-3340ea310b0d.png)

So it fails directly here: https://github.com/electerious/Ackee/blob/master/src/server.js#L56

Any idea about what we can do wrongly?

Also, we created a [nuxt-ackee](https://github.com/bdrtsky/nuxt-ackee) module ✨

**Comment by atinux** [comment]
Actually it is now fixed by using the `develop` branch of Ackee (fixed by https://github.com/electerious/Ackee/pull/84)

**Comment by electerious** [comment]
Thanks for the reminder! I will release the develop branch tomorrow and add `nuxt-ackee` to the related modules section. Thanks a lot for your contribution :)
