### ISSUE TITLE
Error: Server returned with an unhandled status

### ISSUE THREAD

**Issue by nym21** [electerious/ackee-tracker#13]
Hi,

I just finished the setup of the server, everything works fine when I try Ackee with the <script> but with ackee-tracker I get an error. I tried removing parameters but no matter what I do, it still crashes when I call .record()

Here's a photo:

<img width="506" alt="Screen Shot 2020-06-14 at 4 06 54 PM" src="https://user-images.githubusercontent.com/32246972/84595653-62bb8400-ae59-11ea-8e98-ce82ce069fe3.png">

And the code 

```js
    const instance = ackeeTracker.create({
        server: 'https://ackee.gawlik.io',
        domainId: 'acf48a42-b795-4202-834d-e23531572138',
    });

    instance.record({
        siteLocation: window.location.href,
        siteReferrer: document.referrer,
    });
```

Maybe it's stupid, but I really couldn't find the solution,

Anyway, thanks for this great tracker 👍

**Comment by electerious** [comment]
That's interesting. Can you show me the response of the server? It seems that it returns some kind of XML, which shouldn't be the case.

**Comment by nym21** [comment]
Of course I forgot to check that ! My bad, here's the response:

![Screen Shot 2020-06-16 at 4 28 26 PM](https://user-images.githubusercontent.com/32246972/84787962-dfcc3200-afee-11ea-8c0b-c7caf8b1cf76.png)

And here's what's being send:

![Screen Shot 2020-06-16 at 4 28 13 PM](https://user-images.githubusercontent.com/32246972/84787948-db077e00-afee-11ea-8290-7eda974177fe.png)

**Comment by electerious** [comment]
Looks like `document.referrer` returns an empty string instead of `undefined`. I recommend to do the following:

```js
// This will use the default attributes which are polished to not include empty strings
instance.record();
```

```js
// This should work because we're replacing the empty string with undefined
instance.record({
    siteLocation: window.location.href,
    siteReferrer: document.referrer || undefined,
});
```

I've already adjusted the next version to do the normalisation on the server instead. It therefore shouldn't happen in the next big release :)

**Comment by nym21** [comment]
Thanks for the help !
