### ISSUE TITLE
Warning fills logs

### ISSUE THREAD

**Issue by rc1** [electerious/ackee-tracker#20]
Hello.

I'm building server side rendered apps with Next.js. My logs get filled with: "Ackee is not executing automatically because you are using it in an environment without a `window` object'". It would be great if this was removed or only logged once.

Thanks 

https://github.com/electerious/ackee-tracker/blob/0d8034b99f20dc46bb6713624bb6721f33ba5a6f/src/scripts/main.js#L271

**Comment by electerious** [comment]
Makes sense. PR welcome!

**Comment by electerious** [comment]
Done 😊 Will be part of the next release.
