### ISSUE TITLE
What are/is the API URL(s)?

### ISSUE THREAD

**Issue by ghost** [electerious/ackee-tracker#21]
Hello,

I am trying to lock down my instance using Cloudflare Access and they utilize zero-trust access management meaning that all URLs require additional authentication by default, so I am wondering what API URL(s) I need to whitelist so users can still report data, while keeping the admin panel protected.

Edit: I wanted to note that I already have /tracker.js whitelisted, I am talking about the API endpoints that are posted to using the tracker.js script.

Thanks!

**Comment by electerious** [comment]
I guess that whitelisting the tracker and `/api` should be enough. All requests will go through this route.

**Comment by ghost** [comment]
Thanks!
