### ISSUE TITLE
Include Typescript types in this repo

### ISSUE THREAD

**Issue by emschwartz** [electerious/ackee-tracker#39]
Hi @electerious, would you be open to moving the type definitions from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/a245f923a8f79242a376b468350a677f43ed2c00/types/ackee-tracker) into this repo? It seems like it would be easier to keep them in sync.

(Currently the type definition for `instance.record` is missing the `callback`)

**Comment by electerious** [comment]
Thanks for the suggestion, but I'm not a TS user and therefore the wrong person to keep the types in sync.
