### ISSUE TITLE
Enable more data at ackee-tracker

### ISSUE THREAD

**Issue by hamzamu** [electerious/ackee-tracker#40]
Hi, 
I just installed Ackee, and it is wonderful, simple and direct to the point. 
However, I cannot get device data, browser and other related data. I am getting this message: 

`There is either no data available or collecting detailed data is disabled in ackee-tracker.`

How can I enable device and browser data analytics?

<img width="1278" alt="Screen Shot 2021-08-31 at 12 03 51" src="https://user-images.githubusercontent.com/340579/131474830-641447bb-353c-4a5c-a43e-79225ddd63aa.png">

Best, 
Hamza

**Comment by electerious** [comment]
There's an option in ackee-tracker called `detailed` which can be set to `true`: https://github.com/electerious/ackee-tracker#-options

This is how you set the option when using ackee-tracker via a script-tag (`data-ackee-opts` attribute at the end):

```
<script async src="dist/ackee-tracker.min.js" data-ackee-server="https://ackee.example.com" data-ackee-domain-id="hd11f820-68a1-11e6-8047-79c0c2d9bce0" data-ackee-opts='{ "detailed": true }'></script>
```
