### ISSUE TITLE
How to use it basicly ? (what is domainId ?) 

### ISSUE THREAD

**Issue by c0ncentus** [electerious/ackee-tracker#41]
``` Javascript
<script async src="https://ackee.example.com/tracker.js" data-ackee-server="https://ackee.example.com" data-ackee-domain-id="hd11f820-68a1-11e6-8047-79c0c2d9bce0"></script>
```

"domainId {String} Id of the domain." extract from the doc but none steps to have it ...
src => ok
data-ackee-server => ok
data-ackee-domain-id => ??? 

How to create it (data-ackee-domain-id) ? can I fill random string myself ?

**Comment by electerious** [comment]
You can find the domain id in the UI of Ackee when you add or edit a domain in the settings. You will also find the script-tag in the dialog along with all parameters.

**Comment by c0ncentus** [comment]
Thanks, it work 👍
