### ISSUE TITLE
Supporting typescript out of the box

### ISSUE THREAD

**Issue by simonwep** [electerious/ackee-tracker#45]
Hey :) I just wanted to ask if there is any plan on supporting typescript (e.g. shipping / publishing types) natively? There's already a `@types/ackee-tracker` with third-party types...

**Comment by electerious** [comment]
Hey @Simonwep thanks for the suggestion, but I'm not a TS user and therefore the wrong person to maintain the types directly in this package.

**Comment by simonwep** [comment]
That was actually my question, since typescript is a superscript of JS and you provide the actual source code if there is any chance of you providing the types directly :)

**Comment by electerious** [comment]
I know :) I've updated my comment to better answer the question.
