### ISSUE TITLE
Option to switch off interval PATCH

### ISSUE THREAD

**Issue by kolyasapphire** [electerious/ackee-tracker#5]
It would be great to manually set an option per website to disable interval PATCH pinging with the rest of the options in data-ackee-opts attribute.

As I understand time spent on site is not yet displayed on Ackee's frontend and some people may not need this functionality.

**Comment by electerious** [comment]
Thanks for the suggestion. I will keep this issue open to see if more users are interested in such an option.

**Comment by electerious** [comment]
I've reduced the amount of requests. From 5s to every 15s. The upcoming version of Ackee will also display durations.

An option isn't planned.
