### ISSUE TITLE
net::ERR_NETWORK_IO_SUSPENDED

### ISSUE THREAD

**Issue by zhaowenyuan** [electerious/ackee-tracker#6]
After a few minutes of opening the HTML file（http://localhost:52330/demos/create.html）, the browser reports an error:
`ackee-tracker.min.js:1` PATCH http://localhost:3000/domains/2faa8c83-a45c-42a9-8bb3-188492b2ab97/records/f23f257f-845e-4f9b-bd2d-285ab829cbc0 `net::ERR_NETWORK_IO_SUSPENDED`
It might be useful to add the following code:
`xhr.timeout = 6000;`

**Comment by electerious** [comment]
Hey @zhaowenyuan, thanks for letting me know.

I don't think it's worth catching the error. Everything I would do is logging it and that happens anyway.
