### ISSUE TITLE
Filter out bots

### ISSUE THREAD

**Issue by bendotero** [electerious/ackee-tracker#7]
Does the tracker record bots that are visiting the site? If so, is there a way to filter that out other than directly manipulating the DB?

**Comment by electerious** [comment]
There's currently no logic in ackee-tracker to block bots. Do you know a way to detect them?

**Comment by fortinmike** [comment]
Could it be as simple as this to block most bots, or am I missing something? https://stackoverflow.com/a/20084661/167983

Without bot blocking analytics can get quite skewed.

**Comment by electerious** [comment]
@fortinmike This could work. The crawler list is quite big so it would make sense to do this server-side using [`is-ua-bot`](https://github.com/atomantic/is-ua-bot). Or client-side with a smaller list that only contains important crawlers.

**Comment by yehudab** [comment]
@electerious 
Looks like this is open for quite some time. 

I thought I suggest my PR, which does the filtering on client-side, assuming that most bot that do run JS are also those that match the RegEx in the SO post linked by @fortinmike.

**Comment by electerious** [comment]
Merged. Will be part of the next release!
