### ISSUE TITLE
Option to exclude IPs

### ISSUE THREAD

**Issue by styxlab** [electerious/ackee-tracker#9]
I'm authoring a blog and would like to exclude tracking authors/site administrators when they access the website. The IPs from which they access the site are well known, so an option to exclude a list of IPs from tracking would be nice.

**Comment by electerious** [comment]
I don't want to reinvent the wheel and therefore recommend to use a reverse proxy to block IPs. A reverse proxy is the preferred way to "host" Ackee.

Here's a tutorial on how to block IPs using NGINX: https://www.cyberciti.biz/faq/linux-unix-nginx-access-control-howto/

Would this do the job?

**Comment by styxlab** [comment]
Yes, that'll do. Thanks!
